### ISSUE TITLE
This is not an issue Im only looking for Documentation.

### ISSUE THREAD

**Issue by darkhacknet** [gnori-zon/MailSenderBot#3]
Hello Gnori-zon, 

This looks really amazing and its very helpfull, but I have a question, when you will upload the documentation ? It would be great to know how can I made this  script work. Im a little confused, also I dont know how to fill the application.yaml, and also I have no idea how to run this cool tool. 

Thanks in advance.

**Comment by gnori-zon** [comment]
thanks, I will add the documentation within 3 days. In short, telegram has a client that queues emails to RabbitMQ to be sent. You can also use n-number of services that monitor the queue and send messages from it.
